### PR TITLE
Hide kubecontext outside of kube project

### LINKED ISSUE #111: Kubernetes included with Docker 18.09 sets the kubectl-section to always be enabled
## Bug Report

**Current Behavior**
With the recently released Docker 18.09 (Version 2.0.0.0-mac78), I experience that the Kubernetes section is always enabled.  The reason for that is Kubernetes is now included with Docker, and the `kubectl` command is therefore always present.  The current check is only wether if the command is present or not.

**Expected Behavior**
The prompt added with https://github.com/matchai/spacefish/pull/76 should only be visible when needed.  Inside a config folder (Dockerfile, etc.  Don't know how Kube works.)

**Environment**
- Spacefish version: [the output of `echo $SPACEFISH_VERSION`]
1.9
- Fish version: [the output of `fish --version`]
fish, version 2.7.1-1181-g18a163dc
- Fish plugin manager: [e.g. oh-my-fish, fisher, fin]
fundle
- Terminal emulator: [e.g. iTerm, Hyper, Terminator]
kitty
- Operating system: [e.g. OSX 10.13.4, Windows 10]
macOS Mojave

**Possible Solution**

Only load the section when needed.

**Additional context/Screenshots**

Add any other context about the problem here. If applicable, add screenshots to help explain.
screenshot 2018-11-23 at 16 17 03

### PR DESCRIPTION
**Pull request by matchai**
## Description

Add an early return when `kube_context` is not present.

## Motivation and Context

Closes #111 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**

## Checklist:

- [x] I have checked that no other PR duplicates mine
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by matchai** [comment]
I would add a test for this line, but speaking honestly, I don't know how to create a Kubernetes project. I'd appreciate it if anyone can share some insight into how we can test this! 😄

**Comment by Snuggle** [comment]
The indentation on this line has gone swimming! Looks good otherwise, please fix before merging. :blush: 

https://github.com/matchai/spacefish/blob/0b888b0a2bdae470ece1dd838163a4a22b054fb9/functions/__sf_section_kubecontext.fish#L15

**Review by Snuggle — APPROVED** [review]

**Comment by MindTooth** [comment]
Did you notice any changes in rendering speed of the prompt?  Felt like this (kubectl)-check caused the shell to halt some before render det new input line.

Testing without Spacefish and using a built in prompt, and it flies away.

Any way for me to completely disable the Kubernetes section, to test the speed out?

**Comment by matchai** [comment]
This most-recent update should not really affect performance as it's only checking the existence of a variable. We were already performing the kubectl check previously, but not acting on it. 😅 

Yes, by setting `SPACEFISH_KUBECONTEXT_SHOW` to `false`, the section won't appear, skipping the check.

You can add `set -gx SPACEFISH_KUBECONTEXT_SHOW false` to your `config.fish` to disable it.

**Comment by MindTooth** [comment]
Guess it's all the different checks then. :smile:

Thanks.

**Pull request merged**
