### PR TITLE
Have ACPI use only the first battery value

### LINKED ISSUE #124: Battery section: ACPI use only first battery value
It appears this issue would also happen on spacefish, and the solution seems like a rather quick fix. 👍 

## 

> [🐟](https://github.com/matchai/spacefish-bot) **spacefish-bot** — Pull request copied from: https://github.com/denysdovhan/spaceship-prompt/pull/583.

When trying to show battery percentage with ACPI command having with multiple batteries causes bad math expression.

Fixes denysdovhan/spaceship-prompt#245 

For the output of:
```
$ acpi -b 
Battery 0: Unknown, 97%
Battery 1: Unknown, 98%
```

Original logic:
```
$ acpi -b 2>/dev/null | awk '{print $4}' | tr -d '%[,;]'
97
98
```

After piping `acpi -b` through `head -1`:
```
$ acpi -b 2>/dev/null | head -1 | awk '{print $4}' | tr -d '%[,;]'
97
```

### PR DESCRIPTION
**Pull request by matchai**
## Description

Ported the solution used in the following PR: https://github.com/denysdovhan/spaceship-prompt/pull/583

## Motivation and Context

Closes #124 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**

This feature is untested as I have no computer using acpi. I would appreciate it if someone could validate this fix.

## Checklist:

- [x] I have checked that no other PR duplicates mine
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Review by Snuggle — APPROVED** [review]
Looks good to me!
Apologies for being away during the holidays and I hope you enjoyed yours! ☃️💖

**Comment by Snuggle** [comment]
As for testing, I'll be happy to test uhh... Tomorrow if I have free time and can remember!

**Comment by matchai** [comment]
Thank you @Snuggle! Hope you had some enjoyable time off. 😎🌴
I've also been taking it easy the last couple weeks.

Sounds perfect! No pressure if you don't get around to it right away. 😄

**Comment by matchai** [comment]
@Snuggle Just a friendly reminder that this PR needs testing if you've got some free time. 😄 
(Happy new year! 🎉)

**Review by tiffafoo — APPROVED** [review]

**Comment by Snuggle** [comment]
After testing, my prompt uses my wireless mouse's battery and reports 0%. No errors though! :clinking_glasses: 

screenshot from 2019-01-09 09-25-27

`Ubuntu 18.10 on a generic Samsung laptop and a Logitech MX Master (1st gen.) wireless mouse.`

**Comment by Snuggle** [comment]
I can't remember where the conversation was, either on this repo or Spaceship, but there needs to be some logic in place to ignore a 0% battery level. Perhaps to return the first _non-zero_ battery level.

**Comment by Snuggle** [comment]
This pull request _does_ fix the following bug, though and is better than master. I'll try and join in @salmanulfarzy's discussion on how to handle multiple batteries, should be interesting. :slightly_smiling_face: 

screenshot from 2019-01-09 09-33-29

**Review by Snuggle — APPROVED** [review]

**Comment by matchai** [comment]
Yep! This is by no means a perfect solution. Just a better one for the time being. 😃
Thanks for taking the time to manually test it! 🍻

**Comment by salmanulfarzy** [comment]
Did you accidentally revert the original changes (2e2aa9980a44a2074d412bf556843b1867b11738) with this merge commit (2c7bd67d78c94b61a50f61d19dd0d4aea1116baa) or was it intentional ? Seems like the only change now is comment removal :man_shrugging:

**Comment by matchai** [comment]
Oh whoops. That was definitely a slip-up! 😱
Solid catch @salmanulfarzy!

**Pull request merged**
