### PR TITLE
SPACEFISH_GIT_STATUS_SHOW is never checked

### PR DESCRIPTION
**Pull request by hrvoj3e**
SPACEFISH_GIT_STATUS_SHOW can not be turned off - check this variable and return if false

## Motivation and Context

Improves #154 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**

## Checklist:

- [ ] I have checked that no other PR duplicates mine
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by hrvoj3e** [comment]
https://github.com/denysdovhan/spaceship-prompt/blob/master/sections/git_status.zsh
```shell
spaceship_git_status() {
  [[ $SPACESHIP_GIT_STATUS_SHOW == false ]] && return

  spaceship::is_git || return
...
...
```

**Comment by matchai** [comment]
Hey @hrvoj3e. Thank you for the contribution! 😄 
That's a great bug you caught. Before we have this merge in, could you please add a test for this config option so that we can catch future regressions?

The appropriate test file is here: https://github.com/matchai/spacefish/blob/master/tests/__sf_section_git_status.test.fish

**Comment by hrvoj3e** [comment]
Is this OK? 8761549

**Review by matchai — APPROVED** [review]
Yes, looks great!
Thank you for your contribution. 😄

**Pull request merged**
